config/routes.rb
Goschool::Application.routes.draw do

  resources :materials

  mount Ckeditor::Engine => '/ckeditor'

  get "search_engine/search"
  controller :search_engine do
    get 'search_engine/search'
    get 'search_engine/tip'
    get 'search_engine/search_by_view'
  end
  

  controller :teachers do
    get 'teachers'=>:index
    get 'teachers/index'
    get 'teachers/schedules'
    get 'teachers/fast_search'
  end

  controller :tags do
    get 'tags/fast_search'
  end

  resources :student_homeworks do
    collection do
      get :submit_calculate
      get :scores
    end
  end

  resources :homeworks do
    collection do
      get  'index/:id'=>:index
      get  'index/:id/:sid'=>:index #sid is sub_course_id
      get 'list/:id/:type'=>:list
      get 'list/:id/:type/:sid'=>:list
    end
  end

  resources :consultcomments

  resources :achievements do
    collection do
      post :create_sub
      get :sub_achievement
    end
  end
  resources :achievementresults

  resources :welcome
  root :to => 'welcome#index'
  
  resources :comments
  resources :posts do
    collection do
      get 'index/:id'=>:index
      get 'list/:id/:type'=>:list
    end
  end

  controller :files do
    post 'files/attach'=>:attach
    post 'files/remove_attach' =>:remove_attach
    get 'files/download'=>:download
  end

  resources :student_courses do
    collection do
      post :creates
      put :pay
      put :pays
      delete :destroies
    end
  end

  resources :schedules do
    collection do
      get :dates
      get :courses
      get :teachers
      get :teacher
      post :send_email
    end
  end

  resources :students do
    collection do
      get :fast_search
      get ':id/edit'=>:edit
      post '/submit_material'=>:submit_material
      get ':id/:part'=>:show
      get ':id/:part/:ajax'=>:show
      get :detail
    end
  end

  resources :student

  resources :teacher_courses

  resources :sub_courses do
    collection do
      get :teachers
    end
  end

  resources :courses do
    collection do
      get ':id/edit'=>:edit
      get ':id/:part'=>:show
      get ':id/:part/:ajax'=>:show
      get :fast_search
      get :list_search
      get :subs
      post :add_teacher
      get :detail
    end
  end

  resources :settings do
    collection do
      get ':id/:ajax'=>:show
      put :update
    end
  end
  resources :institutions
  mount Resque::Server.new, :at=>"/admin/resque"

  resources :users do
    collection do
      get :schedules
      get :teacher
    end
  end
  resources :custom_views
  resources :logininfos
  resource :subscriptions

  resources :consultations

  resource :logininfo_sessions
  controller :logininfo_sessions do
    match 'logininfo_sessions/destroy' => :destroy
  end

  controller :attachments do
    match 'attachments/:id' => :destroy, :via => "delete"
  end

end

app/views/shares/_admin_aside.html.erb
<aside class="back-index-aside">
     <a class="logo" ></a>
     <ul class="first-ul">
          <li>
               <a href='<%= students_path%>'>学生信息</a>
          </li>
          <li>
               <a>老师信息</a>
          </li>
          <li>
               <a>课程信息</a>
          </li>
     </ul>
     <ul class="second-ul" id="main-navigator-bottom">
          <li>
               <a href='<%= settings_path%>'> <i class="settings icon" data-content="全局配置"></i></a>
          </li>
          <li>
               <i class="smile icon" data-content="我的账户"></i>
          </li>
          <li>
               <i class="mail outline icon" data-content="发送信息"></i>
          </li>
          <li>
              <a href="/logininfo_sessions/destroy"> <i class="sign out icon" data-content="退出账户"></i></a>
          </li>
     </ul>
</aside>

app/views/shares/_bbs_aside.html.erb
<aside class="back-index-condition front-index-condition">
     <header class="back-index-side-header">
     </header>
     <div class="ui vertical menu">
       <% if current_logininfo.is_teacher? %>
           <a class="item <%='active' if @homework_active %>" href="/homeworks/index/<%= session[:teacher_course_id]%>"> <i class="inbox icon"></i> <label>作业</label> </a>
           <a class="item <%='active' if @post_active %>" href="/posts/index/<%= session[:course_id] %>"> <i class="chat outline icon"></i> <label>互动</label> </a>
       <% elsif current_logininfo.is_student? %>
           <a class="item <%='active' if @homework_active %>" href="/homeworks/index/<%= session[:course_id] %>"> <i class="inbox icon"></i> <label>作业</label> </a>
           <a class="item <%='active' if @post_active %>" href="/posts/index/<%= session[:course_id] %>"> <i class="chat outline icon"></i> <label>互动</label> </a>
       <% end %>

     </div>
</aside>

app/views/shares/_file_upload.html.erb
<div class="upload-file">
  <a class="ui button twitter mini" onclick="$('#task-attach-uploader').click()">上传附件(最大为20M)</a>
  <input id="task-attach-uploader" class="task-attach-upload" type="file" style="display: none;" multiple="true" data-url="/files/attach" name="files[]">
  <div id="task-attach-uploader-preview">

  </div>

</div>

<% content_for :javascript_includes do%>
<%= javascript_include_tag "jquery.ui/jquery-ui-1.10.3.custom.min.js"%>
<%= javascript_include_tag "jquery.file.upload/jquery.fileupload.js"%>
<%= javascript_include_tag "_file_upload.js"%>
<% end %>
  
<script type="text/javascript">
  window.onload = function(){
  attach_upload();
  }
</script>

app/views/shares/_index_aside.html.erb
<aside class="back-index-aside">
     <a class="logo" ></a>
     <ul class="first-ul">
          <li>
               <a href="#">学生信息</a>
          </li>
          <li>
               <a>老师信息</a>
          </li>
          <li>
               <a>课程安排</a>
          </li>
     </ul>
     <ul class="second-ul" id="main-navigator-bottom">
          <li>
               <i class="settings icon" data-content="全局配置"></i>
          </li>
          <li>
               <i class="smile icon" data-content="我的账户"></i>
          </li>
          <li>
               <i class="mail outline icon" data-content="发送信息"></i>
          </li>
          <li>
               <i class="sign out icon" data-content="退出账户"></i>
          </li>
     </ul>
</aside>

app/views/shares/_left_aside.html.erb
<aside class="back-index-aside">
  <a class="logo"></a>
  <ul class="first-ul">
    <% if current_logininfo.is_employee? %>
        <li>
          <a class="<%= @active_left_aside=='students' ? 'active' : '' %>" href='<%= students_path %>'>学生信息</a>
        </li>
        <li>
          <a class="<%= @active_left_aside=='courses' ? 'active' : '' %>" href='<%= courses_path %>'>课程信息</a>
        </li>
    <% end %>
    <% if current_logininfo.is_teacher? || current_logininfo.is_student? %>
        <li>
          <a class="<%= @active_left_aside=='homepage' ? 'active' : '' %>" href='<%= current_logininfo.is_teacher? ? teachers_path : student_index_path %>'>我的主页</a>
        </li>
    <% end %>
    <% if current_logininfo.is_student? %>
        <li>
          <a class="<%= @active_left_aside=='achievements' ? 'active' : '' %>" href="/student/<%= current_logininfo.student.id %>">我的成就</a>
        </li>
    <% end %>
  </ul>
  <ul class="second-ul" id="main-navigator-bottom">
    <% if current_logininfo.is_admin? %>
        <li>
          <a href='<%= settings_path %>'> <i class="settings icon" data-content="全局配置"></i></a>
        </li>
    <% end %>
    <li>
      <a href="<%= logininfos_path%>"> <i class="smile icon" data-content="我的账户"></i></a>
    </li>
    <li>
      <a> <i class="mail outline icon" data-content="发送信息"></i></a>
    </li>
    <li>
      <a href="/logininfo_sessions/destroy"> <i class="sign out icon" data-content="退出账户"></i></a>
    </li>
  </ul>
</aside>

app/views/shares/_log_footer.html.erb
<footer class="control-log" id="control-log" state="close">
    <i class="icon double angle right"></i>
    操作记录
</footer>
<footer class="back-index-log" id="back-index-log" >
    <ul>
        <li>2013-10-13 13:00 开始课程 1</li>
        <li>2013-10-13 12:00 开始课程 21</li>
    </ul>
</footer>

app/views/shares/_message_box.html.erb
<div class="message-box" id="MessageBox">
     <p></p>
</div>