config/routes.rb
Goschool::Application.routes.draw do

  resources :materials

  mount Ckeditor::Engine => '/ckeditor'

  get "search_engine/search"
  controller :search_engine do
    get 'search_engine/search'
    get 'search_engine/tip'
    get 'search_engine/search_by_view'
  end
  

  controller :teachers do
    get 'teachers'=>:index
    get 'teachers/index'
    get 'teachers/schedules'
    get 'teachers/fast_search'
  end

  controller :tags do
    get 'tags/fast_search'
  end

  resources :student_homeworks do
    collection do
      get :submit_calculate
      get :scores
    end
  end

  resources :homeworks do
    collection do
      get  'index/:id'=>:index
      get  'index/:id/:sid'=>:index #sid is sub_course_id
      get 'list/:id/:type'=>:list
      get 'list/:id/:type/:sid'=>:list
    end
  end

  resources :consultcomments

  resources :achievements do
    collection do
      post :create_sub
      get :sub_achievement
    end
  end
  resources :achievementresults

  resources :welcome
  root :to => 'welcome#index'
  
  resources :comments
  resources :posts do
    collection do
      get 'index/:id'=>:index
      get 'list/:id/:type'=>:list
    end
  end

  controller :files do
    post 'files/attach'=>:attach
    post 'files/remove_attach' =>:remove_attach
    get 'files/download'=>:download
  end

  resources :student_courses do
    collection do
      post :creates
      put :pay
      put :pays
      delete :destroies
    end
  end

  resources :schedules do
    collection do
      get :dates
      get :courses
      get :teachers
      get :teacher
      post :send_email
    end
  end

  resources :students do
    collection do
      get :fast_search
      get ':id/edit'=>:edit
      post '/submit_material'=>:submit_material
      get ':id/:part'=>:show
      get ':id/:part/:ajax'=>:show
      get :detail
    end
  end

  resources :student

  resources :teacher_courses

  resources :sub_courses do
    collection do
      get :teachers
    end
  end

  resources :courses do
    collection do
      get ':id/edit'=>:edit
      get ':id/:part'=>:show
      get ':id/:part/:ajax'=>:show
      get :fast_search
      get :list_search
      get :subs
      post :add_teacher
      get :detail
    end
  end

  resources :settings do
    collection do
      get ':id/:ajax'=>:show
      put :update
    end
  end
  resources :institutions
  mount Resque::Server.new, :at=>"/admin/resque"

  resources :users do
    collection do
      get :schedules
      get :teacher
    end
  end
  resources :custom_views
  resources :logininfos
  resource :subscriptions

  resources :consultations

  resource :logininfo_sessions
  controller :logininfo_sessions do
    match 'logininfo_sessions/destroy' => :destroy
  end

  controller :attachments do
    match 'attachments/:id' => :destroy, :via => "delete"
  end

end

app/models/student_homework.rb
#encoding: utf-8
class StudentHomework < ActiveRecord::Base
  belongs_to :student
  belongs_to :homework
  belongs_to :tenant
  has_many :attachments,:as=>:attachable,:dependent=>:destroy
  attr_accessible :content, :improved, :marked, :marked_time, :score, :submited_time,:homework_id
  acts_as_tenant(:tenant)

  validate :validate_save
  def self.detail_by_homework_id homework_id,student_id=nil
    q=joins(:student).where(homework_id:homework_id).select("students.id as student_id,students.*,student_homeworks.*")
    q=q.where(student_id:student_id) if student_id
    q
  end
  
  def self.unsubmits  student_id
     student=Student.find_by_id(student_id)
      ids=StudentHomework.where(student_id:student.id).pluck(:homework_id)
      q= student.original_homeworks.where(student_courses:{student_id:student_id},homeworks:{status:false})
       q=q.where("homeworks.id not in (?)",ids) if ids.count>0
       q.select('sub_courses.name as sub_course_name,sub_courses.parent_name as course_name,homeworks.*')
  end
  
  def self.scores student_id,sub_course_id
    joins(:homework=>{:teacher_course=>:sub_course}).joins(:student)
      .where(student_id:student_id,sub_courses:{id:sub_course_id},marked:true)
      .select("student_homeworks.score,student_homeworks.marked_time as time")
  end

  def self.by_type params
   if params[:menu_type].to_i==HomeworkStudentMenuType::UNSUBMIT
      student=Student.find_by_id(params[:student_id])
      ids=StudentHomework.where(student_id:student.id).pluck(:homework_id)
      q= student.original_homeworks.where(student_courses:{student_id:params[:student_id],course_id:params[:id]})
       q=q.where("homeworks.id not in (?)",ids) if ids.count>0
    else
	   q=  joins(:homework=>{:teacher_course=>:sub_course}).joins(:student)
	    .where(student_id:params[:student_id],sub_courses:{course_id:params[:id]})
	    .where(HomeworkStudentMenuType.condition(params[:menu_type]))
	    .select("homeworks.*")
    end
     q=q.where(sub_courses:{id:params[:sub_course_id]}) if params[:sub_course_id]
     q
  end
  
    def  can_resubmit?
      !self.marked
    end
    
  private

  def validate_save
    errors.add(:score,'作业分数不可为空') if self.score.blank? && !self.score.nil? unless self.new_record?
  end
end

app/controllers/student_homeworks_controller.rb
#encoding: utf-8
class StudentHomeworksController < ApplicationController
  before_filter :init_message ,:only=>[:create,:update,:destroy]
  before_filter :get_student_homework , :only=>[:update,:edit,:show,:destroy]
  before_filter :render_nil_msg , :only=>[:update,:destroy]
  before_filter :require_user_as_student,:only=>[:create,:edit]
  skip_before_filter :require_user_as_employee
  def create
    attach=params[:student_homework].slice(:attach)[:attach] if params[:student_homework].has_key?(:attach)
    @student_homework=StudentHomework.new(params[:student_homework].except(:attach))
    Attachment.add(attach,@student_homework)
    @student_homework.student=current_logininfo.student
    @student_homework.submited_time=Time.now
    @msg.content=(@msg.result=@student_homework.save) ? @student_homework.id :  @student_homework.errors.messages
    render :json=>@msg
  end

  def show
    render :json=>@student_homework
  end

  def edit
    render partial:'edit'
  end

  def update
    if params[:student_homework].has_key?(:score)
      params[:student_homework][:marked]=true
      params[:student_homework][:marked_time]=Time.now
    end
    attach=params[:student_homework].slice(:attach)[:attach] if params[:student_homework].has_key?(:attach)
    if @msg.result=@student_homework.update_attributes(params[:student_homework].except(:attach))
      @msg.content=true
      Attachment.add(attach,@student_homework)
    else
    @msg.content=@student_homework.errors.messages
    end
    render :json=>@msg
  end

  def destroy
    @student_homework.destroy
    @msg.result=true
    render :json=>@msg
  end

  def submit_calculate
    @total=StudentHomework.where(student_id:params[:id]).count
    @intime_total=StudentHomework.joins(:homework).where('student_homeworks.submited_time<=homeworks.deadline').where(student_id:params[:id]).count
    render json:[@intime_total,@total]
  end

  def scores
    render json: StudentHomework.scores(params[:id],params[:sid]).map{|sh| {time:sh.time.to_milli,score:sh.score}}
  end

  private

  def init_message
    @msg=Msg.new
  end

  def get_student_homework
    @student_homework=StudentHomework.accessible_by(current_ability).find_by_id(params[:id])
  end

  def render_nil_msg
    unless @student_homework
      @msg.content='不存在此学生作业'
      render :json=>@msg
    end
  end

end

app/helpers/student_homeworks_helper.rb
module StudentHomeworksHelper
end

app/views/student_homeworks/_edit.html.erb
<div class="homework-post-add upload-my-home-work" id="upload-my-home-work">
     <div class="inner">
          <i class="icon remove"></i>
          <p>
               提交我的作业
          </p>
          <div class="content">
               <label>作业内容</label>
               <textarea  class="homework-input" name="content" id="student-homework-content"><%= @student_homework.content%></textarea>
               <div class="upload-file">
                    <%= render 'shares/file_upload'%>
               </div>
               <%@student_homework.attachments.each do |attach|%>
                 <p class="attachment-item upload-file-name resubmit-attachment-item" data-content="<%= attach.name%>" data-variation="inverted" >
                   <%= attach.name%>
                    <i class="icon remove attachment-destroy-icon" attach="<%=attach.id%>"></i>
                </p>
               <%end%>
          </div>
          <div  class="ui button red mini" id="student-homework-submit-button" homework="<%= @student_homework.homework_id%>" student-homework="<%= @student_homework.id%>">
               提交
          </div>
     </div>
</div>

app/views/student_homeworks/_form.html.erb
<div class="ui mini teal button upload-homework"  id="upload-homework">
     提交我的作业
</div>
<div class="homework-post-add upload-my-home-work" id="upload-my-home-work">
     <div class="inner">
          <i class="icon remove"></i>
          <p>
               提交我的作业
          </p>
          <div class="content">
               <label>作业内容</label>
               <textarea  class="homework-input" name="content" id="student-homework-content"></textarea>
               <div class="upload-file">
                    <%= render 'shares/file_upload'%>
               </div>
          </div>
          <div  class="ui button red mini" id="student-homework-submit-button" homework="<%= @homework.id%>">
               提交
          </div>
     </div>
</div>

app/views/student_homeworks/_header.html.erb
<header class="back-index-side-header front-index-side-header" id="front-index-side-header">
     <div class="ui breadcrumb">
          <a class="section active">全部</a>
          <a class="section">听力</a>
          <a class="section">口语</a>
          <a class="section">写作</a>
     </div>
     <a class="ui red mini button" id="add-item">
     <div class="visible content">
          <i class="add icon"></i>
          新建作业
     </div> </a>
     <p>
          <span>托福秋季班</span>的作业
     </p>
</header>

app/views/student_homeworks/_improve.html.erb
<div class="homework-progress-wrap homework-wrap">
     <label>我的进步</label>

     <p>
          最近五次
     </p>

     <div class="icons">
          <%@shs.each do |sh|%>
          <i class="<%= sh.improved ? 'smile' : 'frown'%> icon"></i>
          <%end%>
     </div>
     <p>
          进步次数
     </p>

     <p class="progress_times">
          <i class="icon smile"></i><span><%= @improved%></span>次
     </p>

     <p>
          退步次数
     </p>

     <p class="progress_times">
          <i class="icon frown"></i><span><%= @disimproved%></span>次
     </p>
</div>

app/views/student_homeworks/edit.html.erb
<h1>Editing student_homework</h1>

<%= render 'form' %>

<%= link_to 'Show', @student_homework %> |
<%= link_to 'Back', student_homeworks_path %>

app/views/student_homeworks/index.html.erb
<h1>Listing student_homeworks</h1>

<table>
  <tr>
    <th>Score</th>
    <th>Content</th>
    <th>Improved</th>
    <th>Marked</th>
    <th>Marked time</th>
    <th>Submited time</th>
    <th>Student</th>
    <th>Homework</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @student_homeworks.each do |student_homework| %>
  <tr>
    <td><%= student_homework.score %></td>
    <td><%= student_homework.content %></td>
    <td><%= student_homework.improved %></td>
    <td><%= student_homework.marked %></td>
    <td><%= student_homework.marked_time %></td>
    <td><%= student_homework.submited_time %></td>
    <td><%= student_homework.student %></td>
    <td><%= student_homework.homework %></td>
    <td><%= link_to 'Show', student_homework %></td>
    <td><%= link_to 'Edit', edit_student_homework_path(student_homework) %></td>
    <td><%= link_to 'Destroy', student_homework, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student homework', new_student_homework_path %>

app/views/student_homeworks/new.html.erb
<h1>New student_homework</h1>

<%= render 'form' %>

<%= link_to 'Back', student_homeworks_path %>

app/views/student_homeworks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Score:</b>
  <%= @student_homework.score %>
</p>

<p>
  <b>Content:</b>
  <%= @student_homework.content %>
</p>

<p>
  <b>Improved:</b>
  <%= @student_homework.improved %>
</p>

<p>
  <b>Marked:</b>
  <%= @student_homework.marked %>
</p>

<p>
  <b>Marked time:</b>
  <%= @student_homework.marked_time %>
</p>

<p>
  <b>Submited time:</b>
  <%= @student_homework.submited_time %>
</p>

<p>
  <b>Student:</b>
  <%= @student_homework.student %>
</p>

<p>
  <b>Homework:</b>
  <%= @student_homework.homework %>
</p>


<%= link_to 'Edit', edit_student_homework_path(@student_homework) %> |
<%= link_to 'Back', student_homeworks_path %>