config/routes.rb
Goschool::Application.routes.draw do

  resources :materials

  mount Ckeditor::Engine => '/ckeditor'

  get "search_engine/search"
  controller :search_engine do
    get 'search_engine/search'
    get 'search_engine/tip'
    get 'search_engine/search_by_view'
  end
  

  controller :teachers do
    get 'teachers'=>:index
    get 'teachers/index'
    get 'teachers/schedules'
    get 'teachers/fast_search'
  end

  controller :tags do
    get 'tags/fast_search'
  end

  resources :student_homeworks do
    collection do
      get :submit_calculate
      get :scores
    end
  end

  resources :homeworks do
    collection do
      get  'index/:id'=>:index
      get  'index/:id/:sid'=>:index #sid is sub_course_id
      get 'list/:id/:type'=>:list
      get 'list/:id/:type/:sid'=>:list
    end
  end

  resources :consultcomments

  resources :achievements do
    collection do
      post :create_sub
      get :sub_achievement
    end
  end
  resources :achievementresults

  resources :welcome
  root :to => 'welcome#index'
  
  resources :comments
  resources :posts do
    collection do
      get 'index/:id'=>:index
      get 'list/:id/:type'=>:list
    end
  end

  controller :files do
    post 'files/attach'=>:attach
    post 'files/remove_attach' =>:remove_attach
    get 'files/download'=>:download
  end

  resources :student_courses do
    collection do
      post :creates
      put :pay
      put :pays
      delete :destroies
    end
  end

  resources :schedules do
    collection do
      get :dates
      get :courses
      get :teachers
      get :teacher
      post :send_email
    end
  end

  resources :students do
    collection do
      get :fast_search
      get ':id/edit'=>:edit
      post '/submit_material'=>:submit_material
      get ':id/:part'=>:show
      get ':id/:part/:ajax'=>:show
      get :detail
    end
  end

  resources :student

  resources :teacher_courses

  resources :sub_courses do
    collection do
      get :teachers
    end
  end

  resources :courses do
    collection do
      get ':id/edit'=>:edit
      get ':id/:part'=>:show
      get ':id/:part/:ajax'=>:show
      get :fast_search
      get :list_search
      get :subs
      post :add_teacher
      get :detail
    end
  end

  resources :settings do
    collection do
      get ':id/:ajax'=>:show
      put :update
    end
  end
  resources :institutions
  mount Resque::Server.new, :at=>"/admin/resque"

  resources :users do
    collection do
      get :schedules
      get :teacher
    end
  end
  resources :custom_views
  resources :logininfos
  resource :subscriptions

  resources :consultations

  resource :logininfo_sessions
  controller :logininfo_sessions do
    match 'logininfo_sessions/destroy' => :destroy
  end

  controller :attachments do
    match 'attachments/:id' => :destroy, :via => "delete"
  end

end

app/controllers/student_courses_controller.rb
#encoding: utf-8
class StudentCoursesController < ApplicationController
  before_filter :init_message ,:only=>[:create,:update,:destroy,:creates,:pays,:destroies]
  before_filter :get_student_course , :only=>[:update,:show,:destroy]
  before_filter :render_nil_msg , :only=>[:update,:destroy]
  def create
    @student_course = StudentCourse.new(params[:student_course].strip)
    @msg.content=(@msg.result=@student_course.save) ? @student_course.id :  @student_course.errors.messages
    render :json=>@msg
  end

  # just for update paid
  def update
    @msg.content=@student_course.errors.messages unless @msg.result=@student_course.update_attributes(params[:student_course])
    render :json=>@msg
  end

  def destroy
    @student_course.destroy
    @msg.result=true
    render :json=>@msg
  end

  def creates
    @msg.result=true
    params[:student_courses].each do |param|
      student_course=StudentCourse.new(param[:student_course])
      unless student_course.save
        @msg.result=false
        @msg.content=[] unless @msg.content
        @msg.content<<{:student_id=>param[:student_course][:student_id],:content=>student_course.errors.messages}
      end
    end
    render :json=>@msg
  end

  def pays
    @msg.result=true
    StudentCourse.where(:id=>params[:ids]).update_all(:paid=>params[:paid])
    render :json=>@msg
  end

  def destroies
    @msg.result=true
    StudentCourse.where(:id=>params[:ids]).destroy_all
    render :json=>@msg
  end

  private

  def get_student_course
    @student_course=StudentCourse.find_by_id(params[:id].strip)
  end

  def render_nil_msg
    unless @student_course
      @msg.content='不存在此学生选课'
      render :json=>@msg
    end
  end
end

app/helpers/student_courses_helper.rb
module StudentCoursesHelper
end

app/views/student_courses/_form.html.erb
<%= form_for(@student_course) do |f| %>
  <% if @student_course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student_course.errors.count, "error") %> prohibited this student_course from being saved:</h2>

      <ul>
      <% @student_course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student %><br />
    <%= f.text_field :student %>
  </div>
  <div class="field">
    <%= f.label :course %><br />
    <%= f.text_field :course %>
  </div>
  <div class="field">
    <%= f.label :paid %><br />
    <%= f.check_box :paid %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.number_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/student_courses/edit.html.erb
<h1>Editing student_course</h1>

<%= render 'form' %>

<%= link_to 'Show', @student_course %> |
<%= link_to 'Back', student_courses_path %>

app/views/student_courses/index.html.erb
<h1>Listing student_courses</h1>

<table>
  <tr>
    <th>Student</th>
    <th>Course</th>
    <th>Paid</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @student_courses.each do |student_course| %>
  <tr>
    <td><%= student_course.student %></td>
    <td><%= student_course.course %></td>
    <td><%= student_course.paid %></td>
    <td><%= student_course.status %></td>
    <td><%= link_to 'Show', student_course %></td>
    <td><%= link_to 'Edit', edit_student_course_path(student_course) %></td>
    <td><%= link_to 'Destroy', student_course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student course', new_student_course_path %>

app/views/student_courses/new.html.erb
<h1>New student_course</h1>

<%= render 'form' %>

<%= link_to 'Back', student_courses_path %>

app/views/student_courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Student:</b>
  <%= @student_course.student %>
</p>

<p>
  <b>Course:</b>
  <%= @student_course.course %>
</p>

<p>
  <b>Paid:</b>
  <%= @student_course.paid %>
</p>

<p>
  <b>Status:</b>
  <%= @student_course.status %>
</p>


<%= link_to 'Edit', edit_student_course_path(@student_course) %> |
<%= link_to 'Back', student_courses_path %>